import { ModelsInfo } from "../models/index.js";

export function validateRequiredFields() {
  return (req, res, next) => {
    const route = req.baseUrl.split("/")[1].toLowerCase();
    const modelInfo = ModelsInfo[route];

    if (!modelInfo) {
      return res.status(404).json({
        success: false,
        message: `No model found for route "${route}"`,
      });
    }

    const { model: Model } = modelInfo;
    const attributes = Model.getAttributes();

    const requiredFields = Object.entries(attributes)
      .filter(([key, attr]) => {
        return attr.allowNull === false && !attr._autoGenerated && !attr.primaryKey;
      })
      .map(([key]) => key);

    const missingFields = requiredFields.filter((field) => {
      const value = req.body[field];

      if (value === undefined || value === null) return true;

      if (typeof value === "string" && value.trim() === "") return true;

      return false;
    });

    if (missingFields.length > 0) {
      return res.status(400).json({
        success: false,
        message: `Missing required fields: ${missingFields.join(", ")}`,
      });
    }

    next();
  };
}
